"use client";

import Image from "next/image";
import { AlignCenterHorizontal, AlignCenterVertical, Copy, Eye, EyeOff, Group, Lock, LockOpen, Trash2, Ungroup } from "lucide-react";
import { useDecorPlacement } from "@/components/decor-placement-context";
import { useEditor } from "@/components/editor-context";

export function LayerManager() {
  const placement = useDecorPlacement();
  const editor = useEditor();
  const selectedCount = placement.selectedObjectIds.length;
  const objects = [...placement.placedObjects].sort((a, b) => b.zIndex - a.zIndex);
  return <section className="mt-4 border-t border-[#e1e5ea] pt-4"><div className="flex items-center justify-between"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#69717d]">Capas</p><span className="text-[10px] text-[#69717d]">{objects.length} objetos · {placement.objectGroups.length} grupos</span></div>
    {selectedCount > 1 ? <div className="mt-3 rounded-lg border border-[#b9c9e8] bg-[#f4f7ff] p-2"><p className="text-[10px] font-semibold">{selectedCount} objetos seleccionados</p><div className="mt-2 grid grid-cols-4 gap-1"><button title="Duplicar" aria-label="Duplicar selección" onClick={placement.duplicateSelectedObjects} className="grid h-8 place-items-center rounded border bg-white"><Copy size={13} /></button><button title="Agrupar" aria-label="Agrupar selección" onClick={placement.groupSelectedObjects} className="grid h-8 place-items-center rounded border bg-white"><Group size={13} /></button><button title="Desagrupar" aria-label="Desagrupar selección" onClick={placement.ungroupSelectedObjects} className="grid h-8 place-items-center rounded border bg-white"><Ungroup size={13} /></button><button title="Eliminar" aria-label="Eliminar selección" onClick={placement.deleteSelectedObjects} className="grid h-8 place-items-center rounded border bg-white text-[#b42318]"><Trash2 size={13} /></button></div><div className="mt-1 grid grid-cols-4 gap-1"><button onClick={() => placement.alignSelectedObjects("center-x")} className="grid h-8 place-items-center rounded border bg-white" title="Centrar horizontal"><AlignCenterHorizontal size={13} /></button><button onClick={() => placement.alignSelectedObjects("center-y")} className="grid h-8 place-items-center rounded border bg-white" title="Centrar vertical"><AlignCenterVertical size={13} /></button><button onClick={() => placement.distributeSelectedObjects("horizontal")} className="h-8 rounded border bg-white text-[9px]">Distribuir H</button><button onClick={() => placement.distributeSelectedObjects("vertical")} className="h-8 rounded border bg-white text-[9px]">Distribuir V</button></div><div className="mt-1 grid grid-cols-4 gap-1"><button onClick={() => placement.setSelectedObjectsVisibility(false)} className="h-8 rounded border bg-white text-[9px]">Ocultar</button><button onClick={() => placement.setSelectedObjectsLocked(true)} className="h-8 rounded border bg-white text-[9px]">Bloquear</button><button onClick={() => placement.rotateSelectedObjects(-15)} className="h-8 rounded border bg-white text-[9px]">Girar −15°</button><button onClick={() => placement.rotateSelectedObjects(15)} className="h-8 rounded border bg-white text-[9px]">Girar +15°</button></div></div> : null}
    <div className="mt-3 space-y-2">{placement.objectGroups.map((group) => <article key={group.id} className="rounded-lg border border-[#cbd5e1] bg-[#f8fafc] p-2"><div className="flex items-center gap-2"><Group size={14} /><input aria-label={`Nombre de ${group.name}`} defaultValue={group.name} onBlur={(event) => placement.updateObjectGroup(group.id, { name: event.target.value.trim().slice(0, 80) || group.name })} className="min-w-0 flex-1 bg-transparent text-xs font-semibold" /><button aria-label={group.visible ? "Ocultar grupo" : "Mostrar grupo"} onClick={() => placement.updateObjectGroup(group.id, { visible: !group.visible })}>{group.visible ? <Eye size={13} /> : <EyeOff size={13} />}</button><button aria-label={group.locked ? "Desbloquear grupo" : "Bloquear grupo"} onClick={() => placement.updateObjectGroup(group.id, { locked: !group.locked })}>{group.locked ? <Lock size={13} /> : <LockOpen size={13} />}</button></div><p className="mt-1 pl-6 text-[10px] text-[#69717d]">{group.objectIds.length} objetos</p></article>)}
      {objects.map((object) => <article key={object.id} className={`rounded-lg border bg-white p-2 ${object.selected ? "border-[#2563eb] ring-1 ring-[#2563eb]" : ""}`}><div className="flex items-center gap-2"><button type="button" onClick={(event) => placement.selectPlacedObject(object.id, { additive: event.shiftKey || event.metaKey || event.ctrlKey, toggle: event.metaKey || event.ctrlKey })} className="flex min-w-0 flex-1 items-center gap-2 text-left"><span className="relative h-8 w-8 shrink-0 rounded bg-[#f1eee8]"><Image src={object.assetUrl} alt="" fill unoptimized sizes="32px" className="object-contain" /></span><span className="min-w-0"><span className="block truncate text-[11px] font-semibold">{object.name}</span><span className="block text-[9px] text-[#7a8290]">Capa {object.zIndex + 1}{object.groupId ? " · En grupo" : ""}</span></span></button><button aria-label={object.visible ? `Ocultar ${object.name}` : `Mostrar ${object.name}`} onClick={() => placement.toggleObjectVisibility(object.id)}>{object.visible ? <Eye size={12} /> : <EyeOff size={12} />}</button><button aria-label={object.locked ? `Desbloquear ${object.name}` : `Bloquear ${object.name}`} onClick={() => placement.toggleObjectLock(object.id)}>{object.locked ? <Lock size={12} /> : <LockOpen size={12} />}</button></div></article>)}</div>
    <details className="mt-3 rounded-lg border bg-white p-2"><summary className="cursor-pointer text-xs font-semibold">Paredes y máscaras</summary><div className="mt-2 space-y-1">{editor.masks.map((mask) => <div key={mask.id} className="flex items-center justify-between rounded border px-2 py-1 text-[10px]"><span>{mask.name}</span><span>{mask.visible ? "Visible" : "Oculta"}</span></div>)}</div></details>
  </section>;
}
