"use client";

import Image from "next/image";
import { ArrowDown, ArrowUp, Eye, EyeOff, Lock, LockOpen, Trash2 } from "lucide-react";
import { useDecorPlacement } from "@/components/decor-placement-context";

export function PlacedObjectsList() {
  const placement = useDecorPlacement();
  const objects = [...placement.placedObjects].sort((first, second) => second.zIndex - first.zIndex);
  if (!objects.length) return <section className="mt-4 border-t border-[#e1e5ea] pt-4"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#69717d]">Objetos en la habitación</p><p className="mt-2 rounded-md border border-dashed bg-white p-3 text-xs text-[#7a8290]">Todavía no hay objetos colocados.</p></section>;
  return <section className="mt-4 border-t border-[#e1e5ea] pt-4"><div className="flex items-center justify-between"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#69717d]">Objetos en la habitación</p><span className="text-xs text-[#7a8290]">{objects.length}</span></div><div className="mt-3 space-y-2">{objects.map((object) => <article key={object.id} className={`rounded-lg border bg-white p-2 ${placement.selectedObjectId === object.id ? "border-[#2563eb] ring-1 ring-[#2563eb]" : "border-[#e1e5ea]"}`}><button type="button" onClick={() => placement.selectPlacedObject(object.id)} className="flex w-full items-center gap-2 text-left" aria-label={`Seleccionar ${object.name}`}><span className="relative h-11 w-11 shrink-0 rounded bg-[#f1eee8]"><Image src={object.assetUrl} alt="" fill unoptimized sizes="44px" className="object-contain" /></span><span className="min-w-0 flex-1"><span className="block truncate text-xs font-semibold">{object.name}</span><span className="mt-0.5 block text-[10px] text-[#7a8290]">Capa {object.zIndex + 1}</span></span></button><div className="mt-2 grid grid-cols-5 gap-1"><button type="button" aria-label={object.visible ? `Ocultar ${object.name}` : `Mostrar ${object.name}`} onClick={() => placement.toggleObjectVisibility(object.id)} className="grid h-7 place-items-center rounded border">{object.visible ? <Eye size={12} /> : <EyeOff size={12} />}</button><button type="button" aria-label={object.locked ? `Desbloquear ${object.name}` : `Bloquear ${object.name}`} onClick={() => placement.toggleObjectLock(object.id)} className="grid h-7 place-items-center rounded border">{object.locked ? <Lock size={12} /> : <LockOpen size={12} />}</button><button type="button" aria-label={`Avanzar ${object.name}`} onClick={() => placement.bringForward(object.id)} className="grid h-7 place-items-center rounded border"><ArrowUp size={12} /></button><button type="button" aria-label={`Retroceder ${object.name}`} onClick={() => placement.sendBackward(object.id)} className="grid h-7 place-items-center rounded border"><ArrowDown size={12} /></button><button type="button" aria-label={`Eliminar ${object.name}`} onClick={() => placement.deletePlacedObject(object.id)} className="grid h-7 place-items-center rounded border text-[#b42318]"><Trash2 size={12} /></button></div></article>)}</div></section>;
}
